init
cfn-modules/rds-aurora-serverless-postgres pull request #1
Opened 2019-07-10 11:00 UTC by michaelwittig

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2019-07-10 11:01 UTC, michaelwittig commented
test

2019-07-10 12:41 UTC, michaelwittig commented
test

2019-07-11 13:42 UTC, andreaswittig approved these changes

2019-07-11 14:09 UTC, andreaswittig requested changes

2019-07-11 14:09 UTC, andreaswittig commented on module.yml
> +        FromPort: 3306
Isn't the default port for PostgreSQL `5432`?

2019-07-11 14:13 UTC, michaelwittig commented on module.yml
> +        FromPort: 3306
good catch

2019-07-11 14:16 UTC, merged